#=====================================================================================================
# Program Name     : DirectoryRename
# Input            : Directory name, old extension, new extension (command line arguments)
# Output           : Renames files and logs changes into ProgramLog.txt
# Description      : Renames all files having a specified extension within a directory
#                    and its subdirectories using os.walk and os.rename.
# Author           : Manav Mahadev Jadhav
# Date             : 04/02/2026
#=====================================================================================================

import sys
import os

#------------------------------------------------------------------------
# Function    : ChkDirExist
# Description : Checks whether the given path exists and is a directory
#------------------------------------------------------------------------

def ChkDirExist(Dname):
    Border = "-"*90
    Ret = False

    Ret = os.path.exists(Dname)
    if(Ret == False):
        print("There is no such directory")
        print(Border)
        return Ret
    
    Ret = os.path.isdir(Dname)
    if(Ret == False):
        print("It is not a directory")
        print(Border)
        return Ret
    
    return Ret

#------------------------------------------------------------------------------
# Function    : DirectoryRename
# Description : Renames files from one extension to another within a directory
#------------------------------------------------------------------------------


def DirectoryRename(DirName , ExtensionName1 ,ExtensionName2):
    Border = "-"*90
    Ret = ChkDirExist(DirName)
    if(Ret == False):
        return
    
    fobj = open("ProgramLog.txt","w")
    print("Log file created successfully")
    print(Border)

    fobj.write(Border + "\n")
    fobj.write("This Script is generated by DirectoryRename Automation \n")
    fobj.write(Border + "\n")

    fobj.write(f"The file name whose extension is {ExtensionName1} are converted into : \n")
    for DirectoryName , SubFolderName , FileName in os.walk(DirName):

        
        for fname in FileName :
             if fname.endswith(ExtensionName1):

                root, current_extension = os.path.splitext(fname)
                newfname = root + ExtensionName2

                old_path = os.path.join(DirectoryName, fname)
                new_path = os.path.join(DirectoryName, newfname)

                os.rename(old_path, new_path)
                fobj.write(fname + " -> " + newfname + "\n")
                
    fobj.write(Border + "\n")

    fobj.close()

#-------------------------------------
#  Function    :       main
#  Description :       Driver Code 
#-------------------------------------

def main():

    Border = "-"*90
    print(Border)

    if(len(sys.argv) == 2):
        if((sys.argv[1]== "--h") or (sys.argv[1]== "--H")):
            print("This application is used to rename 1st file extension with 2nd file extension")
            print(Border)
            return

        if((sys.argv[1]== "--u") or (sys.argv[1]== "--U")):
            print("Use the given script as ")
            print(Border)
            print("ScriptName.py Argument1 Argument2 Argument3")   
            print("Argument 1 : Directory Name ")
            print("Argument 2 : File Extension 1 ")
            print("Argument 3 : File Extension 2 ")
            print(Border)
            return
    
    if(len(sys.argv) == 4 ):
        DirectoryRename(sys.argv[1],sys.argv[2],sys.argv[3])
        
    else:
        print("Invalid number of command line arguments")
        print("Use the given flags as : ")
        print("--u : Used to display the usage")
        print("--h : Used to display the help")
        print(Border)
            

    

if __name__ == "__main__":
    main()