#=====================================================================================================
# Program Name     : DirectoryFileSearch
# Input            : Directory name and file extension (command line arguments)
# Output           : Writes names of files with given extension into ProgramLog.txt
# Description      : Traverses a directory structure and logs all files matching
#                    a given extension using os.walk and file handling.
# Author           : Manav Mahadev Jadhav
# Date             : 04/02/2026
#=====================================================================================================

import sys
import os

#------------------------------------------------------------------------
# Function    : ChkDirExist
# Description : Checks whether the given path exists and is a directory
#------------------------------------------------------------------------

def ChkDirExist(Dname):
    Border = "-"*90
    Ret = False

    Ret = os.path.exists(Dname)
    if(Ret == False):
        print("There is no such directory")
        print(Border)
        return Ret
    
    Ret = os.path.isdir(Dname)
    if(Ret == False):
        print("It is not a directory")
        print(Border)
        return Ret
    
    return Ret

#---------------------------------------------------------------------------------------
#  Function    :      DirectoryFileSearch
# Description  :      Searches directory for files with given extension and logs results
#--------------------------------------------------------------------------------------- 
def DirectoryFileSearch(DirName , ExtensionName):
    Border = "-"*90
    Ret = ChkDirExist(DirName)
    if(Ret == False):
        return
    
    fobj = open("ProgramLog.txt","w")
    print("Log file created successfully")
    print(Border)

    fobj.write(Border + "\n")
    fobj.write("This Script is generated by DirectoryFileSearch Automation \n")
    fobj.write(Border + "\n")

    fobj.write(f"The file name whose extension is {ExtensionName} are : \n")
    for DirectoryName , SubFolderName , FileName in os.walk(DirName):

        
        for fname in FileName :
            if fname.endswith(ExtensionName):
            #if ExtensionName in fname : 
                fobj.write(fname +"\n")
    fobj.write(Border + "\n")

    fobj.close()

#-------------------------------------
#  Function    :       main
#  Description :       Driver Code 
#-------------------------------------

def main():

    Border = "-"*90
    print(Border)

    if(len(sys.argv) == 2):
        if((sys.argv[1]== "--h") or (sys.argv[1]== "--H")):
            print("This application is used to display the file name with the extension given by the user")
            print(Border)
            return

        if((sys.argv[1]== "--u") or (sys.argv[1]== "--U")):
            print("Use the given script as ")
            print(Border)
            print("ScriptName.py Argument1 Argument2")   
            print("Argument 1 : Directory Name ")
            print("Argument 2 : File Extension ")
            print(Border)
            return
    
    if(len(sys.argv) == 3 ):
        DirectoryFileSearch(sys.argv[1],sys.argv[2])
        
    else:
        print("Invalid number of command line arguments")
        print("Use the given flags as : ")
        print("--u : Used to display the usage")
        print("--h : Used to display the help")
        print(Border)
            

    

if __name__ == "__main__":
    main()