#=====================================================================================================
# Program Name     : DirectoryRenameAutomation
# Input            : Directory name, source extension, target extension, time interval (CLI arguments)
# Output           : Renames files and logs renamed entries into timestamped log files
# Description      : Traverses a directory structure and periodically renames all files
#                    matching a given extension using os.walk and scheduling.
# Author           : Manav Mahadev Jadhav
# Date             : 10/02/2026
#=====================================================================================================

import sys
import os
import time

#---------------------- Dependency Check ----------------------
try:
    import schedule
except ImportError:
    print("Required module 'schedule' not found.")
    print("Install it using: pip install schedule")
    sys.exit(1)

#------------------------------------------------------------------------
# Function    : ChkDirExist
# Description : Checks whether the given path exists and is a directory
#------------------------------------------------------------------------
def ChkDirExist(Dname):
    Border = "-" * 90

    if not os.path.exists(Dname):
        print("There is no such directory")
        print(Border)
        return False

    if not os.path.isdir(Dname):
        print("It is not a directory")
        print(Border)
        return False

    return True

#------------------------------------------------------------------------------
# Function    : DirectoryRename
# Description : Renames files from one extension to another within a directory
#------------------------------------------------------------------------------

def DirectoryRename(DirName, ExtensionName1 ,ExtensionName2):
    Border = "-" * 90

    if not ChkDirExist(DirName):
        return

    # Updator
    if not ExtensionName1.startswith("."):
        ExtensionName1 = "." + ExtensionName1
    
    if not ExtensionName2.startswith("."):
        ExtensionName2 = "." + ExtensionName2

    timestamp = time.strftime("%Y-%m-%d_%H-%M-%S")
    file_name = f"ProgramLog_{timestamp}.txt"

    print(Border)
    print(f"{file_name} file created successfully")
    print(Border)

    with open(file_name, "w") as fobj:
        fobj.write(Border + "\n")
        fobj.write("This script is generated by Directory Rename Automation\n")
        fobj.write(Border + "\n")
        fobj.write(f"The file name whose extension is {ExtensionName1} are converted into : \n\n")

        for DirectoryName , SubFolderName , FileName in os.walk(DirName):

        
            for fname in FileName :
                if fname.endswith(ExtensionName1):

                    root, current_extension = os.path.splitext(fname)
                    newfname = root + ExtensionName2

                    old_path = os.path.join(DirectoryName, fname)
                    new_path = os.path.join(DirectoryName, newfname)

                    os.rename(old_path, new_path)
                    fobj.write(fname + " -> " + newfname + "\n")

        fobj.write("\n" + Border + "\n")
        fobj.close()

#-------------------------------------
# Function    : main
# Description : Driver code
#-------------------------------------
def main():

    Border = "-" * 50
    print(Border)
    print("----------- Directory Rename Automation ----------")
    print(Border)

    if(len(sys.argv) == 2):

        if((sys.argv[1]== "--h") or (sys.argv[1]== "--H")):
            print("This script is used to:")
            print("1. Create a log file")
            print("2. Log renamed file names of given extension")

        elif((sys.argv[1]== "--u") or (sys.argv[1]== "--U")):
            print("Usage:")
            print("ScriptName.py DirectoryName FileExtension1 FileExtension2 TimeInterval")
            print("DirectoryName   : Directory to search")
            print("FileExtension1  : File extension that needs to be renamed")
            print("FileExtension2  : File extension which has to be renamed by")
            print("TimeInterval    : Time in minutes for periodic execution")

        else:
            print("Invalid option")
            print("Use --h or --u for help")

    elif(len(sys.argv) == 5 ):
        # Filter
        try:
            interval = int(sys.argv[4])
            if interval <= 0:
                raise ValueError
        except ValueError:
            print("TimeInterval must be a positive integer (minutes)")
            return

        print("Directory Name :", sys.argv[1])
        print("Extension1 Name :", sys.argv[2])
        print("Extension2 Name :", sys.argv[3])
        print("Time interval  :", interval, "minutes")

        schedule.every(interval).minutes.do(DirectoryRename, sys.argv[1], sys.argv[2],sys.argv[3])

        print("Directory Rename Automation started at:", time.ctime())
        print("Press Ctrl + C to stop the execution")

        try:
            while True:
                schedule.run_pending()
                time.sleep(1)
        except KeyboardInterrupt:
            print("\nAutomation stopped by user")

    else:
        print("Invalid number of command line arguments")
        print("Use --h or --u for help")

    print(Border)
    print("--------- Thank you for using our script ---------")
    print(Border)

# Entry point
if __name__ == "__main__":
    main()

