#=====================================================================================================
# Program Name     : DirectoryFileSearch
# Input            : Directory name, file extension, time interval (command line arguments)
# Output           : Writes names of files with given extension into timestamped log files
# Description      : Traverses a directory structure and logs all files matching
#                    a given extension using os.walk and file handling.
# Author           : Manav Mahadev Jadhav
# Date             : 10/02/2026
#=====================================================================================================

import sys
import os
import time

#---------------------- Dependency Check ----------------------
try:
    import schedule
except ImportError:
    print("Required module 'schedule' not found.")
    print("Install it using: pip install schedule")
    sys.exit(1)

#------------------------------------------------------------------------
# Function    : ChkDirExist
# Description : Checks whether the given path exists and is a directory
#------------------------------------------------------------------------
def ChkDirExist(Dname):
    Border = "-" * 90

    if not os.path.exists(Dname):
        print("There is no such directory")
        print(Border)
        return False

    if not os.path.isdir(Dname):
        print("It is not a directory")
        print(Border)
        return False

    return True

#---------------------------------------------------------------------------------------
# Function    : DirectoryFileSearch
# Description : Searches the directory for files with the given extension
#               and writes results into a timestamped log file
#---------------------------------------------------------------------------------------
def DirectoryFileSearch(DirName, ExtensionName):
    Border = "-" * 90

    if not ChkDirExist(DirName):
        return

    # Updator
    if not ExtensionName.startswith("."):
        ExtensionName = "." + ExtensionName

    timestamp = time.strftime("%Y-%m-%d_%H-%M-%S")
    file_name = f"ProgramLog_{timestamp}.txt"

    print(Border)
    print(f"{file_name} file created successfully")
    print(Border)

    with open(file_name, "w") as fobj:
        fobj.write(Border + "\n")
        fobj.write("This script is generated by Directory File Search Automation\n")
        fobj.write(Border + "\n")
        fobj.write(f"Files with extension {ExtensionName} are:\n\n")

        for DirectoryName , SubFolderName , FileName  in os.walk(DirName):

            for fname in FileName:
                if fname.endswith(ExtensionName):
                    full_path = os.path.join(DirectoryName,fname)
                    fobj.write(full_path + "\n")

        fobj.write("\n" + Border + "\n")

#-------------------------------------
# Function    : main
# Description : Driver code
#-------------------------------------
def main():

    Border = "-" * 50
    print(Border)
    print("------- Directory File Search Automation ---------")
    print(Border)

    if(len(sys.argv) == 2):

        if((sys.argv[1]== "--h") or (sys.argv[1]== "--H")):
            print("This script is used to:")
            print("1. Create a log file")
            print("2. Log file names of a given extension")

        elif((sys.argv[1]== "--u") or (sys.argv[1]== "--U")):
            print("Usage:")
            print("ScriptName.py DirectoryName FileExtension TimeInterval")
            print("DirectoryName  : Directory to search")
            print("FileExtension  : File extension (example: .py or py)")
            print("TimeInterval   : Time in minutes for periodic execution")

        else:
            print("Invalid option")
            print("Use --h or --u for help")

    elif(len(sys.argv) == 4 ):

        # Filter
        try:
            interval = int(sys.argv[3])
            if interval <= 0:
                raise ValueError
        except ValueError:
            print("TimeInterval must be a positive integer (minutes)")
            return

        print("Directory Name :", sys.argv[1])
        print("Extension Name :", sys.argv[2])
        print("Time interval  :", interval, "minutes")

        schedule.every(interval).minutes.do(DirectoryFileSearch, sys.argv[1], sys.argv[2])

        print("Directory File Search Automation started at:", time.ctime())
        print("Press Ctrl + C to stop the execution")

        try:
            while True:
                schedule.run_pending()
                time.sleep(1)
        except KeyboardInterrupt:
            print("\nAutomation stopped by user")

    else:
        print("Invalid number of command line arguments")
        print("Use --h or --u for help")

    print(Border)
    print("--------- Thank you for using our script ---------")
    print(Border)

# Entry point
if __name__ == "__main__":
    main()

