#=====================================================================================================
# Program Name     : DirectoryDuplicateRemoval
# Input            : Directory name (command line argument)
# Output           : Deletes duplicate files and logs removed files into Log.txt
# Description      : Traverses a directory recursively, calculates MD5 checksum
#                    for each file, detects duplicate files, and removes
#                    duplicate copies while keeping one original.
# Author           : Manav Mahadev Jadhav
# Date             : 04/02/2026
#=====================================================================================================


import sys
import os
import hashlib

#------------------------------------------------------------------------
# Function    : ChkDirExist
# Description : Checks whether the given path exists and is a directory
#------------------------------------------------------------------------

def ChkDirExist(Dname):
    Border = "-"*90
    Ret = False

    Ret = os.path.exists(Dname)
    if(Ret == False):
        print("There is no such directory")
        print(Border)
        return Ret
    
    Ret = os.path.isdir(Dname)
    if(Ret == False):
        print("It is not a directory")
        print(Border)
        return Ret
    
    return Ret

#------------------------------------------------------------------------
# Function    : CheckSumCalculate
# Description : Calculates MD5 checksum of a given file
#------------------------------------------------------------------------

def CheckSumCalculate(file_name):
    
    fobj = open(file_name,"rb")

    hobj = hashlib.md5()

    Buffer = fobj.read(1024)

    while(len(Buffer) > 0):
        hobj.update(Buffer)
        Buffer = fobj.read(1024)

    fobj.close()

    return hobj.hexdigest()

#------------------------------------------------------------------------
# Function    : DirectoryScan
# Description : Scans directory and groups files by checksum
#------------------------------------------------------------------------

def DirectoryScan(DirName = "Demo"):
    Border = "-"*90
    Ret = ChkDirExist(DirName)
    if(Ret == False):
        return
    

    Duplicate={}

    for DirectoryName , SubFolderName , FileName in os.walk(DirName):

        for fname in FileName :
            fname = os.path.join(DirectoryName,fname)
            Ret = CheckSumCalculate(fname)

            if Ret in Duplicate :
                Duplicate[Ret].append(fname)
            else:
                Duplicate[Ret] = [fname]
    
    return Duplicate

#-------------------------------------------------------------------------------
# Function    : DirectoryDuplicateRemoval
# Description : Removes duplicate files based on checksum and logs deletions
#-------------------------------------------------------------------------------

def DirectoryDuplicateRemoval(Path = "Demo"):
    MyDict = DirectoryScan(Path)
    Border = "-"*90

    fobj = open("Log.txt","w")
    print("Log file created successfully")
    print(Border)

    fobj.write(Border + "\n")
    fobj.write("This Script is generated by DirectoryDuplicateRemoval Automation \n")
    fobj.write(Border + "\n")

    Result = list(filter(lambda x : len(x) > 1 , MyDict.values()))

    Count = 0

    for value in Result:
        for subvalue in value:
            Count = Count + 1
            if(Count >1 ):
                os.remove(subvalue)
                fobj.write("Deleted Duplicate file is : "+subvalue+"\n")
        Count = 0
        

#-------------------------------------
#  Function    :       main
#  Description :       Driver Code 
#-------------------------------------

def main():

    Border = "-"*90
    print(Border)

    if(len(sys.argv) == 2):
        if((sys.argv[1]== "--h") or (sys.argv[1]== "--H")):
            print("This application is used to remove duplicate files from the directory")
            print(Border)
            return

        if((sys.argv[1]== "--u") or (sys.argv[1]== "--U")):
            print("Use the given script as ")
            print(Border)
            print("ScriptName.py Argument1 ")   
            print("Argument 1 : Directory Name ")
            print(Border)
            return
    
    if(len(sys.argv) == 2 ):
        DirectoryDuplicateRemoval(sys.argv[1])
        
    else:
        print("Invalid number of command line arguments")
        print("Use the given flags as : ")
        print("--u : Used to display the usage")
        print("--h : Used to display the help")
        print(Border)
            

    

if __name__ == "__main__":
    main()